env:
  ORIGINAL_PROJECT: CeuiLiSA/Pixiv-Shaft
jobs:
  build:
    name: Build apk
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}
    - continue-on-error: true
      name: Clone repo
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build debug apk
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleDebug
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        distributions-cache-enabled: true
    - continue-on-error: true
      if: ${{ !github.head_ref }}
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug
    - continue-on-error: true
      id: get_tag_name
      if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
      name: Get tag name
      run: 'set -x

        version_tag=${GITHUB_REF/refs\/tags\//}

        version_tag_short=`echo $version_tag | awk ''NR==1,/v/{sub(/v/, "");print}''`

        echo "VERSION_TAG=$version_tag" >> $GITHUB_ENV

        echo "VERSION_TAG_SHORT=$version_tag_short" >> $GITHUB_ENV

        '
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
      name: Build release apk
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: assembleRelease
        configuration-cache-enabled: true
        dependencies-cache-enabled: true
        distributions-cache-enabled: true
    - continue-on-error: true
      if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
      name: Deal with release apk
      run: 'cp app/build/outputs/apk/release/app-release.apk app-release.apk

        cp app-release.apk PixShaft_$VERSION_TAG_SHORT.apk

        sha1=`sha1sum app-release.apk | awk ''{ print toupper($1) }''`

        sha256=`sha256sum app-release.apk | awk ''{ print toupper($1) }''`

        echo "APK_SHA1=$sha1" >> $GITHUB_ENV

        echo "APK_SHA256=$sha256" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.ref, 'refs/tags/') && github.repository == env.ORIGINAL_PROJECT
      name: Draft release
      uses: softprops/action-gh-release@v1
      with:
        body: "# \u66F4\u65B0\u5185\u5BB9\n### \u65B0\u589E\n* \n* \n### \u4FEE\u6539\
          \n* \n* \n### \u4FEE\u590D\n* \n* \n\n```\nSHA-1: ${{ env.APK_SHA1 }}\n\
          SHA-256: ${{ env.APK_SHA256 }}\n```\n"
        draft: true
        files: 'PixShaft_${{env.VERSION_TAG_SHORT}}.apk

          '
        name: ${{ env.VERSION_TAG }}
        prerelease: false
        tag_name: ${{ env.VERSION_TAG }}
name: CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
